server:
  port: 8080

spring:
  spring:
    application:
      name: com.deliveryDemo
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/deliveryrestaurant?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
#  redis:
#    host: ${reggie.redis.host}
#    port: ${reggie.redis.port}
#    database: ${reggie.redis.database}
#    password: ${reggie.redis.password}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type:ASSIGN_ID

